### ISSUE TITLE
Add basename function

### ISSUE THREAD

**Issue by Ambrevar** [Shinmera/pathname-utils#10]
Maybe I missed something, but I can't find a direct way the get the "basename" (i.e. the name of the path, should it be a file or a directory).

Indeed, `(pathname-name "foo/")` returns NIL.
To get the name of a directory using the `pathname` API, one option is this:

```lisp
(first (last (pathname-directory (uiop:ensure-directory-pathname pathname))))
```

Really, this would deserve a helper :p  Or does it exist already?

**Comment by Shinmera** [comment]
`pathname-utils:directory-name`

**Comment by Shinmera** [comment]
Though basename is typically equivalent to `pathname-utils:upwards` instead.

**Comment by Ambrevar** [comment]
> `pathname-utils:directory-name`

This won't do the right thing for a non-directory file.

> Though basename is typically equivalent to `pathname-utils:upwards` instead.

Are you sure?

```lisp
> (path:upwards "/foo/bar/baz")
#P"/foo/baz"
```

I would have expected `#P"baz"` instead.

**Comment by Shinmera** [comment]
I edited my comment. Try `parent`.

**Comment by Shinmera** [comment]
Err, wait, nvm. Parent isn't what you want either.

**Comment by Shinmera** [comment]
I honestly don't understand in what case `basename`s behaviour is ever actually correct. Directories and files are very different things. Mushing them together like this seems like a bad idea.

**Comment by Ambrevar** [comment]
I find it useful to have a function that just returns the name of the thing pointed to by the path.

Try `basename` in a Unix shell to see what I mean.

On Unix, directories are files, they are conceptually the same thing.

**Comment by Shinmera** [comment]
They are not conceptually the same thing. They can't be read or written to in Unix either. 'everything is a file' is a lie.

**Comment by Ambrevar** [comment]
But with regard to names, it's fine.

**Comment by Shinmera** [comment]
Fwiw the new `parse-native-namestring` accepts an `:as :directory` which solves this issue at the parsing stage, to ensure the input from the user is already treated correctly.

**Comment by Ambrevar** [comment]
OK, thanks!

**Comment by Shinmera** [comment]
Added `force-directory` [ec85f60](https://github.com/Shinmera/pathname-utils/commit/ec85f606c1d0aeefe4df8449ae1702e416f6e7cb), so this should now be doable either by coercing when parsing, or with `(directory-name (force-directory *))` if absolutely necessary.
