### ISSUE TITLE
`relative-pathname` not relative enough

### ISSUE THREAD

**Issue by 3b** [Shinmera/pathname-utils#11]
on windows:
```lisp
(pathname-utils:relative-pathname "d:/foo/bar" "d:/foo/baz")
;;  #P"d:baz"
```

but

```lisp
(merge-pathnames #P"d:baz" "e:/blah/bar")
;; #P"d:/blah/baz"
```
which makes it hard to use the `face` field in bmfont files

**Comment by Shinmera** [comment]
Hm. I'm not even sure how this could work across devices? Should it just error?

**Comment by 3b** [comment]
`relative-pathname` sees arguments on one device, but includes device in results, expected just `#p"baz"`.

leaving the device in makes it hard to merge with pathnames on any other device, while `#p"baz"` would give a path on the same device as the 'defaults' path.

**Comment by Shinmera** [comment]
Ah, yes, that part I definitely agree with.
