### ISSUE TITLE
file-name misbehaves with wildcards?

### ISSUE THREAD

**Issue by Ambrevar** [Shinmera/pathname-utils#8]
See

```lisp
> (pathname-utils:file-name "[foo]")
"#<PATTERN (:CHARACTER-SET . \"foo\")>"
```

It may also error out:

```lisp
> (pathname-utils:file-name "[foo")
; Debugger entered on #<SB-KERNEL:NAMESTRING-PARSE-ERROR {100BF1FD03}>
```

Is it intentional?  I believe it should parse the namestrings, e.g. with `uiop:parse-native-namestring`.

**Comment by Shinmera** [comment]
It takes a pathname, so your implementation parsing rules apply first before the function even does anything.

**Comment by Ambrevar** [comment]
Sorry, I get the same with `#p"[foo]"`.

Shouldn't `file-name` return NIL for wildcard pathnames?

**Comment by Shinmera** [comment]
It's very questionable whether it should return anything at all for wild pathnames. Erroring seems like the most reasonable course of action if anything.

**Comment by Ambrevar** [comment]
Erroring is fine too.

It's just `"#<PATTERN (:CHARACTER-SET . \"foo\")>"` that does not seem
right at all :)
