### ISSUE TITLE
Wildcard handling

### ISSUE THREAD

**Issue by Ambrevar** [Shinmera/pathname-utils#9]
I find cl:pathname difficult to use because of the wildcard handling which must be constantly parsed and converted back, e.g. with a file name like `[foo`.

Does pathname-utils provide some simplification in this regard?
I see that it has `*wild-file*`, etc., but I don't understand what they are for.  @shinmera Can you provide an example use?

**Comment by Shinmera** [comment]
Those are for constructing wild pathnames. There's unfortunately no native namestring parsing utility that escapes wild characters in pathname-utils yet (#2)

**Comment by Ambrevar** [comment]
Do you have concrete plans or should I go ahead and submit a patch?

**Comment by Shinmera** [comment]
If you have time to implement a portable native namestring parser and printer then by all means send a PR. Note, using `uiop` is out of the question.

**Comment by Ambrevar** [comment]
Why?

**Comment by Shinmera** [comment]
Because this is an independent utility library. I don't want to pull in the mess that  is UIOP for no reason.

**Comment by Ambrevar** [comment]
Maybe we can extract uiop:parse-native-namestring then.

**Comment by Shinmera** [comment]
Implemented now.

**Comment by Shinmera** [comment]
The latest bunch.

**Comment by Ambrevar** [comment]
I see, thanks!
